import {test,expect} from "@playwright/test";
import {execSync} from "node:child_process";
import {randomUUID,createHash} from "node:crypto";
import {writeFile,mkdir} from "node:fs/promises";
import JSZip from "jszip";

test("seven controls own every mutation and byte transition",async({page})=>{
 const status=JSON.parse(execSync("npx supabase status --output json",{encoding:"utf8"})),api=status.API_URL,stamp=Date.now(),tenant=randomUUID(),otherTenant=randomUUID(),doc=randomUUID(),doc2=randomUUID(),relationship=randomUUID(),exceptionId=randomUUID(),obligation=randomUUID(),connector=randomUUID();
 const sql=q=>execSync(`docker exec supabase_db_shikigami-cypher-online psql -U postgres -d postgres -v ON_ERROR_STOP=1 -Atc "${q.replaceAll('"','\\"')}"`,{encoding:"utf8"}).trim(),acl=()=>sql("select coalesce(jsonb_agg(jsonb_build_object('schema',table_schema,'table',table_name,'privilege',privilege_type) order by table_schema,table_name,privilege_type),'[]') from information_schema.role_table_grants where grantee='service_role'");
 const aclBefore=acl(),call=async(path,init={})=>{const r=await fetch(api+path,init),text=await r.text();if(!r.ok)throw Error(`${path} ${r.status} ${text}`);return text?JSON.parse(text):null},h=token=>({apikey:status.ANON_KEY,authorization:`Bearer ${token}`,"content-type":"application/json"}),signup=async label=>call("/auth/v1/signup",{method:"POST",headers:h(status.ANON_KEY),body:JSON.stringify({email:`${label}-${stamp}@local.test`,password:`Pilot!${stamp}${label}`})}),owner=await signup("owner"),other=await signup("other");
 sql(`insert into public.cypher_tenants(id,legacy_id,name) values('${tenant}','pilot-${stamp}','Pilot'),('${otherTenant}','other-${stamp}','Other');insert into public.cypher_memberships(tenant_id,user_id,role,status) values('${tenant}','${owner.user.id}','owner','active'),('${otherTenant}','${other.user.id}','owner','active');insert into public.cypher_documents(id,tenant_id,legacy_id,document_type,original_path,original_hash,status,mime_type,size_bytes,created_by) values('${doc}','${tenant}','ocr-${stamp}','invoice','${tenant}/fixture/ocr.pdf','${"b".repeat(64)}','accepted','application/pdf',1,'${owner.user.id}'),('${doc2}','${tenant}','po-${stamp}','purchase_order','${tenant}/fixture/po.pdf','${"c".repeat(64)}','accepted','application/pdf',1,'${owner.user.id}');insert into public.cypher_relationships(id,tenant_id,source_document_id,related_document_id,relationship_type,detector_version,explanation,status) values('${relationship}','${tenant}','${doc}','${doc2}','po_match','fixture-v1','{"rule":"po","facts":["PO-1"]}','candidate');insert into public.cypher_exceptions(id,tenant_id,document_id,kind,status) values('${exceptionId}','${tenant}','${doc}','ocr_mismatch','open');insert into public.cypher_obligations(id,tenant_id,document_id,state,amount_minor,currency,due_at,confirmed_by,confirmed_at,policy_version) values('${obligation}','${tenant}','${doc}','confirmed_outstanding',12345,'USD','2026-08-01','${owner.user.id}',now(),'fixture-v1');insert into public.cypher_connectors(id,tenant_id,connector_type,display_name,status) values('${connector}','${tenant}','simulated','Local emulator','active')`);
 const before={documents:Number(sql(`select count(*) from public.cypher_documents where tenant_id='${tenant}'`)),extractions:0,corrections:0,artifacts:0,deliveries:0},network=[];page.on("response",r=>{if(r.url().includes("/api/cypher/v1")){const request=r.request(),serialized=JSON.stringify({headers:request.headers(),body:request.postData()});network.push({url:r.url(),status:r.status(),method:request.method(),service_key_present:serialized.includes(status.SERVICE_ROLE_KEY)})}});await page.addInitScript(({token,cfg})=>{sessionStorage.setItem("cypher_local_access_token",token);sessionStorage.setItem("cypher_pilot_config",JSON.stringify(cfg))},{token:owner.access_token,cfg:{document:doc,relationship,exception:exceptionId,obligation,connector,package:null}});await page.goto("/cypher-pilot.html");
 const click=async name=>{const b=page.locator(`[data-workflow="${name}"]`);await b.click();await expect(b).toHaveAttribute("data-pass",/true|false/);if(await b.getAttribute("data-pass")!=="true")throw Error(`${name}: ${await page.locator("#result").textContent()}`);return JSON.parse(await page.locator("#result").textContent()).data};
 const intake=await click("intake");expect(intake.state).toBe("finalized");expect(sql(`select count(*) from public.cypher_trusted_upload_receipts where document_id='${intake.document_id}'`)).toBe("1");
 await click("ocr-validation");expect(sql(`select count(*) from public.cypher_extraction_runs where document_id='${doc}'`)).toBe("1");expect(sql(`select count(*) from public.cypher_corrections where document_id='${doc}'`)).toBe("1");
 await click("relationships");await click("exceptions");await click("obligations-aging");const generated=await click("evidence-exports");await page.evaluate(id=>window.cypherPilotConfig.package=id,generated.package);
 const downloaded={};for(const a of generated.artifacts){const response=await page.request.get(`/api/cypher/v1/artifacts/${a.id}`,{headers:{authorization:`Bearer ${owner.access_token}`}});expect(response.ok()).toBe(true);const body=Buffer.from(await response.body());expect(response.headers()["x-content-sha256"]).toBe(createHash("sha256").update(body).digest("hex"));downloaded[a.type]=body}expect(downloaded.export_csv.toString()).toContain("document_id,status");expect(JSON.parse(downloaded.export_json.toString()).status).toBe("validated");const zip=await JSZip.loadAsync(downloaded.export_xlsx);expect(zip.file("xl/workbook.xml")).toBeTruthy();
 const delivered=await click("secure-emulated-delivery");expect(sql(`select status from public.cypher_deliveries where id='${delivered.delivery}'`)).toBe("delivered");expect(sql(`select count(*) from public.cypher_delivery_attempts where delivery_id='${delivered.delivery}'`)).toBe("1");expect(sql(`select count(*) from public.cypher_destination_receipts where delivery_id='${delivered.delivery}'`)).toBe("1");
 const otherResult=await page.evaluate(async token=>(await fetch("/api/cypher/v1/documents",{headers:{authorization:`Bearer ${token}`}})).json(),other.access_token),anonStatus=await page.evaluate(async()=> (await fetch("/api/cypher/v1/documents")).status),aclAfter=acl();expect(otherResult.documents).toEqual([]);expect(anonStatus).toBe(401);expect(aclAfter).toBe(aclBefore);expect(await page.content()).not.toContain(status.SERVICE_ROLE_KEY);
 const after={documents:Number(sql(`select count(*) from public.cypher_documents where tenant_id='${tenant}'`)),extractions:Number(sql(`select count(*) from public.cypher_extraction_runs where tenant_id='${tenant}'`)),corrections:Number(sql(`select count(*) from public.cypher_corrections where tenant_id='${tenant}'`)),artifacts:Number(sql(`select count(*) from public.cypher_artifacts where tenant_id='${tenant}'`)),deliveries:Number(sql(`select count(*) from public.cypher_deliveries where tenant_id='${tenant}'`))},noServiceKey=network.every(item=>!item.service_key_present),evidence={schema:"cypher-batch-d/browser-worker-owned-v4",generated_at:new Date().toISOString(),before,after,network,download_hashes:Object.fromEntries(Object.entries(downloaded).map(([k,v])=>[k,createHash("sha256").update(v).digest("hex")])),other_tenant_denied:true,anon_denied:true,no_service_key:noServiceKey,service_role_acl_before:JSON.parse(aclBefore),service_role_acl_after:JSON.parse(aclAfter),pass:after.documents===before.documents+1&&after.extractions===1&&after.corrections===1&&after.artifacts===5&&after.deliveries===1&&noServiceKey&&aclAfter===aclBefore};await mkdir("reports",{recursive:true});await writeFile("reports/cypher-batch-d-browser-pilot-evidence.json",JSON.stringify(evidence,null,2)+"\n");expect(evidence.pass).toBe(true);
});
