import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
for(const language of ['en','es']) test(`real local Worker/D1 journey ${language}`,async({page,request})=>{
  await page.setViewportSize(language==='es'?{width:390,height:844}:{width:1440,height:900});
  await page.goto(`/shirabe.html?lang=${language}`);
  await expect(page.locator('html')).toHaveAttribute('lang',language);
  await page.keyboard.press('Tab');
  expect(await page.evaluate(()=>document.activeElement!==document.body)).toBe(true);
  await page.locator('[data-mode="guided"]').click();
  for(const [name,value] of Object.entries({name:'Synthetic Operator',company:`Synthetic Only ${language}`,email:`synthetic-${language}@example.invalid`,role:'Synthetic owner',industry:'Synthetic test'}))await page.locator(`[name="${name}"]`).fill(value);
  await page.locator('[name="company_size"]').selectOption({label:'10–49'});await page.locator('#next').click();
  await page.locator('[name="problem_category"]').selectOption('delays');
  await page.locator('[name="problem"]').fill('Synthetic approvals arrive late and need repeated manual reconstruction.');
  await page.locator('[name="last_example"]').fill('Synthetic fictional item waited two days.');await page.locator('#next').click();
  for(const name of ['trigger','participants','tools','source_of_truth','failure_point'])await page.locator(`[name="${name}"]`).fill('Synthetic fictional workflow evidence only.');
  await page.locator('[name="frequency"]').selectOption('weekly');await page.locator('[name="monthly_volume"]').fill('12');await page.locator('#next').click();
  for(const name of ['consequence','evidence_available','desired_outcome','attempts','constraints'])await page.locator(`[name="${name}"]`).fill('Synthetic fictional workflow evidence only; no customer data.');
  for(const [name,value]of Object.entries({loss_basis:'unknown',integrity_concern:'none',workforce_constraint:'adequate',evidence_conflict:'no',disruption:'none',sensitivity:'none'}))await page.locator(`[name="${name}"]`).selectOption(value);
  await page.locator('#next').click();await page.locator('[name="consent"]').check();
  const accessibility=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze();
  expect(accessibility.violations.filter(v=>['critical','serious'].includes(v.impact))).toEqual([]);
  await page.waitForTimeout(4100);
  const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/shirabe-intake'));
  await page.locator('#submit').click();const response=await responsePromise;
  expect(response.status()).toBe(201);const result=await response.json();
  await expect(page.locator('#result-reference')).toHaveText(result.reference);
  const replay=await request.post('/api/shirabe-intake',{data:response.request().postDataJSON()});
  expect(replay.status()).toBe(200);expect((await replay.json()).reference).toBe(result.reference);
  const headers={authorization:'Bearer synthetic-admin-only'};
  for(const next_state of ['claimed','completed'])expect((await request.post(`/api/shirabe/admin/intakes/${result.reference}/routing`,{headers,data:{next_state}})).status()).toBe(200);
  expect((await request.post('/api/shirabe/admin/reconcile',{headers,data:{limit:2}})).status()).toBe(200);
  const receipts=await(await request.get('/__test/receipts')).json();
  expect(receipts.intakes.find(x=>x.id===result.reference)).toMatchObject({language,status:'closed'});
  expect(receipts.notifications).toBe(receipts.intakes.length);
  expect(receipts.outbox.every(x=>x.status==='delivered')).toBe(true);
});
