import { describe,expect,it } from "vitest";
import { backupRestore,measureLoad,migrateLegacy,recoverOutbox,snapshotDigest,syntheticLegacySnapshot } from "../lib/cypher-batch-d.js";
describe("Batch D sandbox acceptance",()=>{
 it("migrates synthetic D1/R2 snapshots with provenance, equality, quarantine and deterministic replay",()=>{const source=syntheticLegacySnapshot(),before=snapshotDigest(source),one=migrateLegacy(source),two=migrateLegacy(source,one.target);expect(one.evidence).toMatchObject({source_unchanged:true,target_counts:{records:14,objects:14,receipts:28,quarantine:1},tenant_isolation:true,object_byte_hash_equality:true});expect(snapshotDigest(source)).toBe(before);expect(two.evidence.inserted).toEqual({records:0,objects:0});expect(two.evidence.replayed).toEqual({records:14,objects:14});});
 it("rejects a conflicting replay",()=>{const source=syntheticLegacySnapshot(),one=migrateLegacy(source);source.records[0].payload.amount_minor++;expect(()=>migrateLegacy(source,one.target)).toThrow("migration_replay_conflict");});
 it("restores private bytes, database state, authz evidence, outbox and checkpoints",()=>{const one=migrateLegacy(syntheticLegacySnapshot());one.target.outbox=[{idempotency_key:"k",status:"pending"}];one.target.checkpoints=[];const {evidence}=backupRestore(one.target);expect(evidence).toMatchObject({counts_equal:true,hashes_equal:true,outbox_equal:true,checkpoints_equal:true,rpo_ms:0,rls_authz:{cross_tenant_denied:true,viewer_write_denied:true}});expect(evidence.rto_ms).toBeGreaterThanOrEqual(0);});
 it("resumes pending outbox once across stop/start",async()=>{const state={outbox:[{idempotency_key:"k",status:"pending"}],checkpoints:[]};let writes=0;await recoverOutbox(state,async()=>({write:++writes}));state.outbox[0].status="pending";await recoverOutbox(state,async()=>({write:++writes}));expect(writes).toBe(1);expect(state.checkpoints).toHaveLength(1);});
 it("records explicit load percentiles, concurrency, errors, thresholds and resources",async()=>{const result=await measureLoad(async()=>{}, {requests:100,concurrency:10});expect(result).toMatchObject({requests:100,concurrency:10,error_rate:0,pass:true});expect(result.p99_ms).toBeGreaterThanOrEqual(0);expect(result.resource.rss_bytes).toBeGreaterThanOrEqual(0);});
});
