import { describe, expect, it } from "vitest";
import { approvedEndpoint, confinedPath, dispatchDelivery, liveAdapter, LocalDestinationEmulator, SupabasePrivateStorageAdapter, verifyPrivateUpload } from "../lib/cypher-batch-c.js";
const tenant="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", intentId="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const digest=async b=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",b))].map(x=>x.toString(16).padStart(2,"0")).join("");
function store(bytes, mutate={}) { const objects=new Map([[`${tenant}/${intentId}/original.pdf`,{bytes,version:"v1"}]]); return { objects,
  upload:async(p,b)=>{if(objects.has(p))throw Error("overwrite");objects.set(p,{bytes:new Uint8Array(b),version:"synthetic"});}, head:async p=>{const o=objects.get(p);return o&&{size:mutate.badSize??o.bytes.length,version:mutate.swap?(o.version+Math.random()):o.version};},
  async *download(p){const b=objects.get(p).bytes;yield mutate.partial?b.slice(0,-1):b;}, delete:async p=>objects.delete(p) }; }
describe("Batch C trusted Storage verifier",()=>{
 it("uses synthetic API operations, streamed digest, immutable atomic finalization",async()=>{const bytes=new TextEncoder().encode("private-object"), s=store(bytes), calls=[];const result=await verifyPrivateUpload({intent:{id:intentId,tenant_id:tenant,state:"awaiting_upload",requested_size:bytes.length,object_path:`${tenant}/${intentId}/original.pdf`},bytes:new Uint8Array([1,2]),store:s,db:{atomicFinalize:async r=>{calls.push(r);return "doc";}}});expect(result).toBe("doc");expect(calls[0]).toMatchObject({content_hash:await digest(bytes),size_bytes:bytes.length,storage_version:"v1"});expect([...s.objects.keys()]).toEqual([`${tenant}/${intentId}/original.pdf`]);});
 for(const [name,mutate] of [["missing",{missing:true}],["truncation",{partial:true}],["race/swap",{swap:true}],["size mismatch",{badSize:99}]]) it(`fails ${name} without finalizing`,async()=>{const bytes=new Uint8Array([1,2,3]),s=store(bytes,mutate);if(mutate.missing)s.objects.clear();let finalized=false;await expect(verifyPrivateUpload({intent:{id:intentId,tenant_id:tenant,state:"awaiting_upload",requested_size:3,object_path:`${tenant}/${intentId}/original.pdf`},bytes:new Uint8Array([9]),store:s,db:{atomicFinalize:async()=>{finalized=true;}}})).rejects.toThrow();expect(finalized).toBe(false);});
 it("rejects path traversal and cross tenant",()=>{expect(()=>confinedPath(tenant,intentId,`${tenant}/../x`)).toThrow();expect(()=>confinedPath(tenant,intentId,`${intentId}/${intentId}/x`)).toThrow();});
});
describe("bounded delivery adapters and dispatcher",()=>{
 it.each(["drive","sharepoint","onedrive","sftp","webhook","object_storage"])("emulates %s with independently verified readback/idempotency",async kind=>{const bytes=new Uint8Array([1,2,3]),d=await digest(bytes),a=new LocalDestinationEmulator(kind,{url:"http://127.0.0.1/hook",hostKey:"k",pinnedHostKey:"k"}),job={tenantId:tenant,key:"safe/file",bytes,sourceDigest:d,idempotencyKey:"idem-1234",oauth:{expiresAt:Date.now()+1000,revoked:false,scopes:["https://www.googleapis.com/auth/drive.file","Files.ReadWrite"]}},ledger={get:async()=>null,atomicRecord:async(_j,r)=>r};const one=await dispatchDelivery(job,a,ledger),two=await dispatchDelivery(job,a,ledger);expect(one.status).toBe("delivered_verified");expect(two).toEqual(one);});
 it("requires digest for verified and tests OAuth, host key, partial, cancellation",async()=>{const bytes=new Uint8Array([1,2,3]),d=await digest(bytes),base={tenantId:tenant,key:"safe/file",bytes,sourceDigest:d,idempotencyKey:"idem-1234"},validOauth={expiresAt:Date.now()+1000,revoked:false,scopes:["https://www.googleapis.com/auth/drive.file"]},ledger={get:async()=>null,atomicRecord:async(_j,r)=>r};expect((await dispatchDelivery({...base,oauth:validOauth},new LocalDestinationEmulator("drive",{omitDigest:true}),ledger)).status).toBe("delivered_unverified");for(const a of [new LocalDestinationEmulator("drive",{}),new LocalDestinationEmulator("sftp",{hostKey:"bad",pinnedHostKey:"good"}),new LocalDestinationEmulator("drive",{partial:true})])await expect(dispatchDelivery({...base,oauth:a.kind==="drive"?{expiresAt:0,scopes:["write"]}:undefined},a,ledger)).rejects.toThrow();const c=new AbortController();c.abort();await expect(dispatchDelivery({...base,oauth:validOauth},new LocalDestinationEmulator("drive"),ledger,{signal:c.signal})).rejects.toThrow("cancelled");});
 it("blocks live adapters and SSRF/redirect-style endpoints",()=>{expect(()=>liveAdapter({})).toThrow("blocked");for(const url of ["http://evil.test/x","http://127.0.0.1@evil.test/x","https://127.0.0.1/x"])expect(()=>approvedEndpoint(url,{local:true})).toThrow();});
 it("uses authenticated official private Storage HTTP routes",async()=>{const calls=[];const adapter=new SupabasePrivateStorageAdapter({origin:"http://127.0.0.1:54321",bucket:"private-documents",token:"user-jwt",apikey:"anon-key",fetchImpl:async(url,init)=>{calls.push({url,init});return new Response(null,{status:init.method==="HEAD"?200:204,headers:{"content-length":"3",etag:'"v1"'}});}});await adapter.upload(`${tenant}/${intentId}/x`,new Uint8Array([1,2,3]));expect(await adapter.head(`${tenant}/${intentId}/x`)).toEqual({size:3,version:'"v1"'});expect(calls[0].url).toContain("/storage/v1/object/private-documents/");expect(calls[1].url).toContain("/storage/v1/object/authenticated/private-documents/");expect(calls[0].init.headers.authorization).toBe("Bearer user-jwt");});
 it("recovers a lost response after the destination write with the stable job key",async()=>{const bytes=new Uint8Array([1,2,3]),d=await digest(bytes),a=new LocalDestinationEmulator("object_storage",{outageAfterWrite:true}),job={tenantId:tenant,key:"safe/file",bytes,sourceDigest:d,idempotencyKey:"stable-job"},ledger={get:async()=>null,atomicRecord:async(_j,r)=>r};const result=await dispatchDelivery(job,a,ledger);expect(result).toMatchObject({status:"delivered_verified",attemptKey:"stable-job",recovered:true});});
 it("rejects every immutable request-field conflict on ledger replay without writing",async()=>{const bytes=new Uint8Array([1,2,3]),d=await digest(bytes),base={tenantId:tenant,key:"safe/file",bytes,sourceDigest:d,idempotencyKey:"immutable-key",jobId:"job-1"};for(const mutate of [j=>({...j,tenantId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc"}),j=>({...j,key:"other/file"}),j=>({...j,sourceDigest:"f".repeat(64)}),j=>({...j,bytes:new Uint8Array([1,2,3,4])}),j=>({...j,jobId:"job-2"})]){const a=new LocalDestinationEmulator("object_storage"),records=new Map(),ledger={get:async(t,k)=>records.get(`${t}:${k}`)||records.get(`original:${k}`),atomicRecord:async(j,r)=>(records.set(`original:${j.idempotencyKey}`,r),r)};await dispatchDelivery(base,a,ledger);const before=[...a.objects.entries()].map(([k,v])=>[k,[...v]]);await expect(dispatchDelivery(mutate(base),a,ledger)).rejects.toThrow("idempotency_conflict");expect([...a.objects.entries()].map(([k,v])=>[k,[...v]])).toEqual(before);}});
 it("rejects immutable conflicts in adapter replay even when ledger lost its response",async()=>{const bytes=new Uint8Array([4,5,6]),d=await digest(bytes),a=new LocalDestinationEmulator("object_storage"),ledger={get:async()=>null,atomicRecord:async(_j,r)=>r},base={tenantId:tenant,key:"safe/file",bytes,sourceDigest:d,idempotencyKey:"adapter-key",jobId:"stable-job"};await dispatchDelivery(base,a,ledger);const before=[...a.objects.keys()];await expect(dispatchDelivery({...base,key:"different/file"},a,ledger)).rejects.toThrow("idempotency_conflict");expect([...a.objects.keys()]).toEqual(before);});
 it("binds ledger replay to the exact destination kind",async()=>{const bytes=new Uint8Array([7]),d=await digest(bytes),base={tenantId:tenant,key:"safe/file",bytes,sourceDigest:d,idempotencyKey:"kind-key",jobId:"kind-job"},records=new Map(),ledger={get:async(_t,k)=>records.get(k),atomicRecord:async(j,r)=>(records.set(j.idempotencyKey,r),r)};await dispatchDelivery(base,new LocalDestinationEmulator("object_storage"),ledger);const other=new LocalDestinationEmulator("sftp",{hostKey:"k",pinnedHostKey:"k"});await expect(dispatchDelivery(base,other,ledger)).rejects.toThrow("idempotency_conflict");expect(other.objects.size).toBe(0);});
});
